# Generated by Django 5.0.4 on 2024-05-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.CharField(max_length=212),
        ),
    ]
